#!/bin/bash
cd /opt
mkdir Tools && cd Tools
mkdir "Information Gathering" && cd "Information Gathering"
git clone --recursive https://github.com/Gameye98/AstraNmap
git clone --recursive https://github.com/UndeadSec/EvilURL
git clone --recursive https://github.com/ciku370/OSIF
git clone --recursive https://github.com/Cvar1984/Easymap
git clone --recursive https://github.com/Gameye98/AstraNmap
git clone --recursive https://github.com/evait-security/weeman
git clone --recursive https://github.com/exlinee/MaxSubdoFinder
git clone --recursive https://github.com/jofpin/trape
git clone --recursive https://github.com/Tuhinshubhra/RED_HAWK
git clone --recursive https://github.com/Lulz3xploit/LittleBrother
git clone --recursive https://github.com/thewhiteh4t/seeker
git clone --recursive https://github.com/s0md3v/ReconDog
git clone --recursive https://github.com/bibortone/D-Tech
git clone --recursive https://github.com/mishakorzik/IpHack
git clone --recursive https://github.com/sullo/nikto
mkdir ismtp && cd ismtp
wget https://raw.githubusercontent.com/crunchsec/ismtp/master/ismtp.py
cd /opt/Tools
mkdir Exploitation && cd Exploitation
git clone --recursive https://www.github.com/threat9/routersploit
git clone --recursive https://github.com/commixproject/commix
git clone --recursive https://github.com/kuburan/txtool
git clone --recursive https://github.com/Moham3dRiahi/XAttacker
git clone --recursive https://github.com/karjok/fim
cd /opt/Tools
mkdir "Sniffing & Spoofing" && cd "Sniffing & Spoofing"
git clone --recursive https://github.com/d4az/hack-gmail
git clone --recursive https://github.com/4w4k3/KnockMail
git clone --recursive https://github.com/thewhiteh4t/pwnedOrNot
git clone --recursive https://github.com/Curioo/emailpyspam
git clone --recursive https://github.com/mishakorzik/Gmail-Hack
git clone --recursive https://github.com/mishakorzik/Email-Spammer
cd /opt/Tools
mkdir "Web Attack" && cd "Web Attack"
git clone --recursive https://github.com/mishakorzik/AdminHack
git clone --recursive https://github.com/ebrandel/takeover
git clone --recursive https://github.com/UltimateHackers/Blazy
git clone --recursive https://github.com/sqlmapproject/sqlmap
git clone --recursive https://github.com/websploit/websploit
git clone --recursive https://github.com/LOoLzeC/SH33LL
git clone --recursive https://github.com/s0md3v/sqlmate
git clone --recursive https://github.com/mishakorzik/py-ddoser
git clone --recursive https://github.com/mishakorzik/Ultra-DDos
git clone --recursive https://github.com/urbanadventurer/WhatWeb
git clone --recursive https://github.com/xmendez/wfuzz
cd /opt/Tools
mkdir "Cam Hacking" && cd "Cam Hacking"
git clone --recursive https://github.com/AngelSecurityTeam/Cam-Hackers
git clone --recursive https://github.com/noob-hackers/grabcam
git clone --recursive https://github.com/Devil-Tigers/CamHack
cd /opt/Tools
mkdir "RATs" && cd "RATs"
git clone --recursive https://github.com/knassar702/pyshell
git clone --recursive https://github.com/kinghacker0/WishFish
cd /opt/Tools
mkdir "SQL Injection" && cd "SQL Injection"
git clone --recursive https://github.com/UndeadSec/Debinject
git clone --recursive https://github.com/Terror696/Vitus2.0
git clone --recursive https://github.com/mishakorzik/Infect
cd /opt/Tools
mkdir "Social Media" && cd "Social Media"
git clone --recursive https://github.com/evildevill/instahack
git clone --recursive https://github.com/IAmBlackHacker/Facebook-BruteForce
git clone --recursive https://github.com/sherlock-project/sherlock
git clone --recursive https://github.com/ALBINPRAVEEN/finduser
git clone --recursive https://github.com/mishakorzik/UserFinder
cd /opt/Tools
mkdir "SMS" && cd "SMS"
git clone --recursive https://github.com/3UMOBKA/SMS-Bomber-300-Free
git clone --recursive https://github.com/8hakan8/AresBomb
git clone --recursive https://github.com/HACK3RY2J/Anon-SMS
git clone --recursive https://github.com/FSystem88/spymer
git clone --recursive https://github.com/TheSpeedX/TBomb
git clone --recursive https://github.com/Edwardboytv/duplo-bomber
git clone --recursive https://github.com/Hackeralok119/Anonymoussms
cd /opt/Tools
mkdir "Vulnerability Analysis" && cd "Vulnerability Analysis"
git clone --recursive https://github.com/floriankunushevci/rang3r
git clone --recursive https://github.com/TechnicalMujeeb/TM-scanner
git clone --recursive https://github.com/Gameye98/AstraNmap
cd /opt/Tools
mkdir "DarkSearch" && cd "DarkSearch"
git clone --recursive https://github.com/josh0xA/darkdump
cd /opt/Tools
mkdir "Phishing" && cd "Phishing"
git clone --recursive https://github.com/htr-tech/zphisher
git clone --recursive https://github.com/AbirHasan2005/ShellPhish
git clone --recursive https://github.com/hangetzzu/saycheese
git clone --recursive https://github.com/mishakorzik/Mask-Phish.Termux
git clone --recursive https://github.com/thewhiteh4t/seeker
git clone --recursive https://github.com/DeepSociety/AIOPhish
git clone --recursive https://github.com/Viralmaniar/I-See-You.git
git clone --recursive https://github.com/DarkSecDevelopers/HiddenEye-Legacy
git clone --recursive https://github.com/An0nUD4Y/blackeye
git clone --recursive https://github.com/Nishant2009/NPhish
cd /opt/Tools
mkdir "Hash Cracking" && cd "Hash Cracking"
git clone --recursive https://github.com/ciku370/hasher
git clone --recursive https://github.com/thamahaxor/hasherdoid
git clone --recursive https://github.com/ciku370/hash-generator
git clone --recursive https://github.com/s0md3v/Hash-Buster
cd /opt/Tools
mkdir "Wordlists" && cd "Wordlists"
git clone --recursive https://github.com/Keshav2136/wlcreator
git clone --recursive https://github.com/UndeadSec/GoblinWordGenerator
git clone --recursive https://github.com/Viralmaniar/SMWYG-Show-Me-What-You-Got
cd /opt/Tools
mkdir "XSS" && cd "XSS"
git clone --recursive https://github.com/menkrep1337/XSSCon
git clone --recursive https://github.com/Ekultek/XanXSS
git clone --recursive https://github.com/s0md3v/XSStrike
cd /opt/Tools
mkdir "Other Stuff" && cd "Other Stuff"
git clone --recursive https://github.com/deadbits/Intersect-2.5
git clone --recursive https://github.com/mishakorzik/Free-Proxy
cd /opt/Tools
